name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - name: Install dotenv
        run: go get github.com/joho/godotenv
      - name: Load environment variables
        run: go run -mod=mod go get github.com/joho/godotenv/cmd/godotenv
      - name: Load dotenv file
        run: go run -mod=mod github.com/joho/godotenv/cmd/godotenv
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./controllers
